services:
  web:
    image: antikevin/unidesk-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    command: npm run start
